import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    /* 1. Added h-full and bg-blue-600 to lock the root height and color */
    <html lang="en" className="h-full bg-blue-600">
      <body
        /* 2. Added h-full, m-0, p-0, and overflow-hidden to lock the body */
        className={`${geistSans.variable} ${geistMono.variable} h-full m-0 p-0 overflow-hidden antialiased`}
      >
        {children}
      </body>
    </html>
  );
}